---
default_stages: [pre-commit]

default_install_hook_types: [pre-commit, commit-msg]

ci:
  autoupdate_commit_msg: 'pre-commit: autoupdate hooks'
  autofix_prs: false
  # docker is not supported on pre-commit.ci
  skip: [shellcheck]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/talos-systems/conform
    rev: v0.1.0-alpha.27
    hooks:
      - id: conform
        stages:
          - commit-msg

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
      - id: markdownlint-fix

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
    -   id: shellcheck
        args: ["--severity=warning"]

  - repo: local
    hooks:
      - id: remark-root-dir
        name: Checks if the remark-templates and static content is placed in root directory
        entry: ./scripts/check-remark-root.sh
        language: script
        types_or: [html, markdown]
